### ISSUE TITLE
Are inactive shims no longer disabled?

### ISSUE THREAD

**Issue by noahgaertner** [asdf-community/asdf-direnv#144] opened 2022-04-10 10:23 UTC
Added this to #10, where it appeared to be fixed initially, but then it occurred to me that adding a comment to an issue that was closed two and a half years ago was perhaps not the best for visibility, so I've opened a new issue.

asdf-direnv used to (at least according to #10) delete inactive shims (which base asdf still does not for whatever reason). Did this change get reverted at some point? I've been using asdf-direnv for over a year now, and it's been great, but I just installed mambaforge (basically miniconda/miniforge) alongside my previous python 3.10.4 install, and whenever I type clear in zsh without the active python version being mambaforge, I get an error saying mambaforge needs to be my active python version. To my understanding, this commit should have fixed that issue, so do I need to do something else to make it work or is it just no longer supported?

_Originally posted by @noahgaertner in https://github.com/asdf-community/asdf-direnv/issues/10#issuecomment-1094238147_

**Comment by vic** [comment] 2022-04-10 18:58
It's never been part of `asdf-direnv` to remove anything from your PATH automatically. If you don't want asdf shims to be part of your PATH, consider following the instruction on README (under `Pro tips` look for `Getting $ASDF_DIR/shims out of the PATH.`).

I've never used miniconda nor mambaforge, but I believe they distribute common utilities (like the `clear` command you mention), I suppose it's sufficient for you to remove shims from your path. Hope I'm understanding correctly what you need. Hopefully other people having more experience with conda stuff here can help.

**Comment by michi-zuri** [comment] 2022-04-11 07:47
Dear @noahgaertner, 
The commit you are referring to was actually just changes to the Readme, so it still depended on how you set up your system. 

The thing is: miniconda, anaconda and mambarforge installed trough asdf python provide a ton of shims, which pollute the system even when they are not active. The issue is in asdf-python not dealing properly with conda and it doesn't seem the issue is fixed yet: https://github.com/danhper/asdf-python/issues/44

What you need to do to get conda working properly with asdf is: getting rid of shims in your path, using direnv-asdf and moving the conda init output from your bashrc to the direnvrc. Especially the last part is a bit strange to figure out, but I got it working once, I wish you good luck!

All the best
Michi

**Comment by noahgaertner** [comment] 2022-04-11 16:34
> It's never been part of `asdf-direnv` to remove anything from your PATH automatically. If you don't want asdf shims to be part of your PATH, consider following the instruction on README (under `Pro tips` look for `Getting $ASDF_DIR/shims out of the PATH.`).
> 
> I've never used miniconda nor mambaforge, but I believe they distribute common utilities (like the `clear` command you mention), I suppose it's sufficient for you to remove shims from your path. Hope I'm understanding correctly what you need. Hopefully other people having more experience with conda stuff here can help.

This appears to have worked for my issue w/ clear specifically. IDK if there will be any side effects, but seems to be working for now so 🤷🏻‍♂️. No clue what @michi-zuri meant with conda init being in direnvrc (I never had it in my zshrc either, but that's probably my fault), but I'll look into it this weekend when I have more free time.

**Comment by vic** [comment] 2022-06-06 05:57
I'm closing this, but please feel free to share better instructions for conda here, in case that might happen to help someone in the future.

**Closed by vic** 2022-06-06 05:57 UTC
