### ISSUE TITLE
New install giving "Error generating asdf cached envrc"

### ISSUE THREAD

**Issue by comfortablynick** [asdf-community/asdf-direnv#102] opened 2022-03-04 22:52 UTC
I pulled my dotfiles onto a new machine and installed the asdf components I use on a few other machines. I can't get it to load the .envrc and it just gives me this error. I have no idea how to troubleshoot it. I get the error even if `direnv 2.30.3` is the only thing in .tool-versions.

Output of `direnv status`:
```
direnv exec path /home/nick/.asdf/installs/direnv/2.30.3/bin/direnv
DIRENV_CONFIG /home/nick/.config/direnv
bash_path /usr/bin/bash
disable_stdin false
warn_timeout 5s
whitelist.prefix []
whitelist.exact map[]
Loaded RC path /home/nick/.envrc
Loaded watch: ".envrc" - 2022-03-04T16:39:30-06:00
Loaded watch: ".local/share/direnv/allow/673651c9e89f949abdf9bfbb3528b9f66cdcfe2f77671709fa47435508685ebc" - 2022-03-04T16:39:36-06:00
Loaded RC allowed false
Loaded RC allowPath
Found RC path /home/nick/.envrc
Found watch: ".envrc" - 2022-03-04T16:39:30-06:00
Found watch: ".local/share/direnv/allow/673651c9e89f949abdf9bfbb3528b9f66cdcfe2f77671709fa47435508685ebc" - 2022-03-04T16:39:36-06:00
Found RC allowed true
Found RC allowPath /home/nick/.local/share/direnv/allow/673651c9e89f949abdf9bfbb3528b9f66cdcfe2f77671709fa47435508685ebc
```

I do have `source "$(asdf direnv hook asdf)"` as the first line in my ~/.config/direnv/direnvrc.

Any help would be appreciated.

**Comment by jfly** [comment] 2022-03-05 00:49
@comfortablynick, can you include the output of a command where this "Error generating asdf cached envrc" gets printed? I don't see it in the `direnv status` output you included.

**Comment by comfortablynick** [comment] 2022-03-05 00:52
It happens anytime the env file is being sourced. For example `direnv reload`:

```
direnv: loading ~/.envrc
direnv: using asdf
direnv: Error generating asdf cached envrc
```

**Comment by jfly** [comment] 2022-03-05 06:40
Ah, darn, that's disappointingly useless output. I don't know what's wrong, but can give you some pointers for debugging.

You're definitely going into this `if` statement: https://github.com/asdf-community/asdf-direnv/blob/895397d8ac0dd44a23e1dffdce1d7c227ec7aa47/lib/commands/command-hook-asdf.bash#L4, which means that you would probably see the same thing if you run `asdf direnv _asdf_cached_envrc`. For example, here's what happens on my machine:

```
$ asdf direnv _asdf_cached_envrc
/home/jeremy/.asdf/installs/direnv/2.30.3/env/1940818189-157964819-2853654360-3000772363
$ echo $?
0
```

(Run this from whatever directory you're running `direnv reload` from) Note the 0 exit code I got. I bet you'll see something else. If I'm guessing right, you're crashing somewhere in `_asdf_cached_envrc` (which is in `~.asdf/plugins/direnv/lib/commands/command.bash` on my machine). I'd just start debugging my way through that file (you could start by adding a `set -x` to the top of the file to get a lot of output). Hopefully this all makes sense!

(Tangentially related: it would be quite nice if asdf-direnv could provide a backtrace when things like this randomly go wrong. Is that something we've ever considered trying to add, @smorimoto @vic?)

**Comment by vic** [comment] 2022-03-05 15:55
@jfly We have not yet considered, but I guess something like this could be of help:

- Adding a function to out `command.bash` that simply enables `set -x`, so people can debug with:
  `asdf direnv _set_x _asdf_cached_envrc`

   such a function (feel free to use a better name ^^)  might simply be: 
   ```bash
   function _set_x() {
      set -x # perhaps also enable other internal logging by setting an env-var.
      "${@}"
   }
   ```

Note: All debugging output should always be printed to STDERR since the output of functions like `_asdf_cached_envrc` is captured and expected to be a file name, and on failure, any output written to STDOUT would simply not be shown: https://github.com/asdf-community/asdf-direnv/blob/master/lib/commands/command-hook-asdf.bash#L4

Also mentioning such debugging facility on the README could be awesome for people having this kind of trouble.

**Comment by comfortablynick** [comment] 2022-03-05 17:00
@jfly When I run `asdf direnv _asdf_cached_envrc` I get no output, just a return code of 1.

Adding `set -x` to the top of the file gives me a ton of output of source code. If I delete `set -eo pipefail`, I get more output:

```
direnv: loading ~/.envrc
direnv: using asdf
/home/nick/.asdf/plugins/direnv/lib/commands/command.bash:13: /lib/utils.bash: No such file or directory
direnv: Creating env file /home/nick/.asdf/installs/direnv/2.30.3/env/89915010-3101997489-152555524-1972995409
/home/nick/.asdf/plugins/direnv/lib/commands/command.bash:94: get_plugin_path: command not found
find: ‘’: No such file or directory
/home/nick/.asdf/plugins/direnv/lib/commands/command.bash:122: find_versions: command not found
/home/nick/.asdf/plugins/direnv/lib/commands/command.bash:122: find_versions: command not found
direnv: loading ~/.asdf/installs/direnv/2.30.3/env/89915010-3101997489-152555524-1972995409
direnv: export +LOADED_ENVRC
```

It exports my test variable but doesn't put python on PATH.

**Comment by jfly** [comment] 2022-03-05 17:03
> If I delete `set -eo pipefail`

Can you leave that in? That's bash's "exit when a command fails" directive. If you remove it, you're going to just skip over the failing command.

> Adding set -x to the top of the file gives me a ton of output of source code

Yes please, let's see it all!

**Comment by jfly** [comment] 2022-03-05 17:07
Oh, actually this is probably where things are going wrong:

> /home/nick/.asdf/plugins/direnv/lib/commands/command.bash:13: /lib/utils.bash: No such file or directory

It's trying to load `/lib/utils.bash`, which definitely doesn't exist. Here's the relevant code: https://github.com/asdf-community/asdf-direnv/blob/6426f1336c7d06d1a12404b1df349a3ecf8d8490/lib/commands/command.bash#L15.

Could you share the output of `asdf info | grep ASDF_DIR`, and if that doesn't print anything, how about the full `asdf info`?

**Comment by comfortablynick** [comment] 2022-03-05 19:31
@jfly Interesting. `ASDF_DIR` isn’t there — in fact, no env vars are set.

I ran (in fish) `set -gx ASDF_DIR $HOME/.asdf` and suddenly it worked. Now it seems to work even without that variable. I notice it’s not set on my other machine either.

Thank you for finding that. I’m guessing that means it should be set somewhere in the source code?

**Comment by glasserc** [comment] 2022-03-05 22:07
I just hit this too. (I'm also using `fish`!) The first time I set up `asdf` I hit it too: https://github.com/asdf-community/asdf-direnv/issues/55. `ASDF_DIR` is set by the toplevel `asdf.fish`, which the README for this project tells us not to use directly (instead using `lib/asdf.fish`). I can reliably reproduce the `Error generating asdf cached envrc` when I remove the `ASDF_DIR` variable using `set -e` and reliably cause it to work when I re-export it (using `set -x`).

**Comment by jfly** [comment] 2022-03-06 00:04
Oh, shoot! This is as simple as "things are broken if you don't have a `ASDF_DIR` environment variable. I have one set, and didn't think to test without one.

I was wildly misunderstanding `asdf info` when I wrote https://github.com/asdf-community/asdf-direnv/commit/d86c5e2fd9ebb5679818a1f84c7e2c623c3421fe. I thought it would be smart enough to build up an `ASDF_DIR` variable if you didn't already have one.

As you both already know, a workaround for now is to just explicitly set `ADSF_DIR` in your shell configuration. I can work on a fix for the underlying problem later today.

**Comment by jfly** [comment] 2022-03-06 01:22
@comfortablynick @glasserc I just sent out a PR with a fix for this: https://github.com/asdf-community/asdf-direnv/pull/104. I'd appreciate if you could try it out and report back!

**Closed** 2022-03-06 06:47 UTC

**Comment by comfortablynick** [comment] 2022-03-06 13:09
Thanks @jfly, it seems to be working fine for me.

**Comment by glasserc** [comment] 2022-03-07 15:14
I can also confirm it works. Thanks for the fast turnaround!
